### PR TITLE
Update to use latest versions of gems

### PR DESCRIPTION
**Pull request by epmatsw**
Specifically, the cocoapods gem that the Gemfile.lock specified was 0.35, while the build process actually required 0.37. This should fix that as well as pulling in updated versions of the other gems.

Note that the tests are failing in the branch (at least on my machine). However, I can't tell if that's a pre-existing issue or if it's caused by this since I can't get the project to build without this change. If someone with a working build environment could chime in one way or the other, that would be nice.

### CODE REVIEW

**Comment by epmatsw** [comment]
Fixes #128

**Comment by jakecraige** [comment]
Looks great. CI is passing which is nice. I'll pull it down to make sure it's still passing locally and then merge. Thanks!

**Comment by jakecraige** [comment]
Looks good! When I pulled down locally and after I `bundle install`d, I got some linker errors but once I `pod install`d it all worked. Maybe that'll fix your local errors?

**Comment by jakecraige** [comment]
Merged in https://github.com/thoughtbot/Tropos/commit/4dd7a6eddc0a643f2ca33145738325192e2e7694

**Pull request closed without merging**
