### PR TITLE
Update dependencies to fix bitcode linker errors when building for device

### PR DESCRIPTION
**Pull request by sharplet**
This change updates both Mixpanel and HockeySDK to new minor versions that include support for bitcode.

### CODE REVIEW

**Comment by sharplet** [comment]
This build failure was hidden because CI doesn't currently build for device. I'm going to look into setting up a device build as part of this PR.

**Comment by gfontenot** [comment]
👍 Should be possible to build for device by using `platform=iOS/Generic` in the build script. Maybe have it build and run the tests, then do a second build for device?

**Comment by sharplet** [comment]
I've pushed a new `bin/archive` script that ultimately performs an `xcodebuild archive`. The `archive` action builds for device, and I think having a successful `archive` step is a stronger signal from CI than a `build` that targets the generic device destination. Let me know what you think.

**Comment by gfontenot** [comment]
makes sense to me 👍

**Pull request merged**
