### PR TITLE
Add polish localisation

### PR DESCRIPTION
**Pull request by tailec**

### CODE REVIEW

**Comment by tomkowz** [comment]
Looks good for me. Let's wait for answers from @jakecraige about unused keys.

**Comment by gfontenot** [comment]
@tomkowz Thanks for reviewing this! In the future, can you make sure to make comments on the Files tab of the PR, as opposed to on the commit itself? That way it's easier to see when issues have been fixed, because the comment is collapsed once the diff changes for that line.

**Comment by tomkowz** [comment]
@gfontenot np. Yeah, thanks for advice, will remember. That was my first github review.

**Comment by gfontenot** [comment]
No worries, I appreciate you putting eyes on it.

**Comment by gfontenot** [comment]
I'll look into those unused keys and get back to you.

**Comment by sharnik** [comment]
+1 confirmation on this being valid Polish.

**Comment by jakecraige** [comment]
@tomkowz Thanks for bringing up the unused keys and reviewing this.

Thanks @tailec for the translations :+1:

**Comment by jakecraige** [comment]
Merged in 8d4cf280c39fd3184f1ed0d22f232aa2587e3525

**Pull request closed without merging**
