### PR TITLE
Bump version to 1.1.1

### PR DESCRIPTION
**Pull request by klaaspieter**
This supersedes #160 and includes all of the latest changes.

### CODE REVIEW

**Comment by jakecraige** [comment]
🐎 🐎

**Comment by klaaspieter** [comment]
I added fastlane _and_ shipped a beta using it. Fastlane can use our [match repo] so no-one ever has to share certificates again.

[match repo]: https://github.com/fastlane/fastlane/tree/master/match

**Comment by klaaspieter** [comment]
Wondering if I should merge this into master. I initially didn't because I didn't want push notifications to hold back another release, but it looks like push notifications _are_ the next release.

@jakecraige mind giving this a last look before I merge?

**Comment by jakecraige** [comment]
Works for me!

**Pull request merged**
